// <auto-generated />
using System;
using AECI.ICM.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AECI.ICM.Data.Migrations
{
    [DbContext(typeof(ICMDbContext))]
    [Migration("20191112085536_InitialDbCreate")]
    partial class InitialDbCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AECI.ICM.Data.Entities.ICM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BranchManager");

                    b.Property<string>("ControlStatement");

                    b.Property<bool>("FinanceFunctionCheck");

                    b.Property<bool>("RegionalAccountant");

                    b.Property<int?>("SectionDetailId");

                    b.HasKey("Id");

                    b.HasIndex("SectionDetailId");

                    b.ToTable("ICM");
                });

            modelBuilder.Entity("AECI.ICM.Data.Entities.SectionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Section");

                    b.Property<string>("SectionName");

                    b.HasKey("Id");

                    b.ToTable("SectionDetail");
                });

            modelBuilder.Entity("AECI.ICM.Data.Entities.ICM", b =>
                {
                    b.HasOne("AECI.ICM.Data.Entities.SectionDetail", "SectionDetail")
                        .WithMany()
                        .HasForeignKey("SectionDetailId");
                });
#pragma warning restore 612, 618
        }
    }
}
