// <auto-generated />
using System;
using AECI.ICM.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AECI.ICM.Data.Migrations
{
    [DbContext(typeof(ICMDbContext))]
    partial class ICMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AECI.ICM.Data.Entities.ICM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BranchManager");

                    b.Property<string>("Comments");

                    b.Property<string>("ControlStatement");

                    b.Property<bool>("FinanceFunctionCheck");

                    b.Property<bool>("RegionalAccountant");

                    b.Property<int?>("SectionDetailId");

                    b.HasKey("Id");

                    b.HasIndex("SectionDetailId");

                    b.ToTable("ICM");
                });

            modelBuilder.Entity("AECI.ICM.Data.Entities.SectionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Section");

                    b.Property<string>("SectionName");

                    b.HasKey("Id");

                    b.ToTable("SectionDetail");
                });

            modelBuilder.Entity("AECI.ICM.Data.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EnableWarning");

                    b.Property<string>("SignatureLocation");

                    b.Property<DateTime>("WarningCuttOffDate");

                    b.Property<string>("WarningEmail");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("AECI.ICM.Data.Entities.SettingEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BranchManagerEmail");

                    b.Property<string>("BranchManagerName");

                    b.Property<string>("RegionalAccountantEmail");

                    b.Property<string>("RegionalAccountantName");

                    b.Property<int?>("SettingId");

                    b.HasKey("Id");

                    b.HasIndex("SettingId");

                    b.ToTable("SettingEmails");
                });

            modelBuilder.Entity("AECI.ICM.Data.Entities.ICM", b =>
                {
                    b.HasOne("AECI.ICM.Data.Entities.SectionDetail", "SectionDetail")
                        .WithMany()
                        .HasForeignKey("SectionDetailId");
                });

            modelBuilder.Entity("AECI.ICM.Data.Entities.SettingEmail", b =>
                {
                    b.HasOne("AECI.ICM.Data.Entities.Setting")
                        .WithMany("Emails")
                        .HasForeignKey("SettingId");
                });
#pragma warning restore 612, 618
        }
    }
}
